### ISSUE TITLE
pants integration

### ISSUE THREAD

**Issue by mansu** [sourcegraph/srclib-python#17]
Hi, 

I am working on a repo that uses pants here at Twitter[1]. Have a couple of questions about making srclib-python pants aware. 

a) What does it take to make src-lib python pants aware?
b) Looking at the code it looks like the scanner, dep-resolver and grapher all depend on jedi? Am I right?
c) Since srclib-python is relies on jedi (which in-turn uses disttools/setuptools) for static analysis, Is it better to create a separate toolchain based on pants? What parts of the current python tool chain be used for this analysis? If we were to replace just parts of the toolchain, what parts should we be replacing? Any pointers will be helpful.

Thanks!

[1] https://pantsbuild.github.io/

**Comment by sqs** [comment]
Hi Suman! That's fantastic to hear and we would love to help in any way possible.

> a) What does it take to make src-lib python pants aware?
> b) Looking at the code it looks like the scanner, dep-resolver and grapher all depend on jedi? Am I right?

The scanner is partially still written in Go (see [Scan](https://sourcegraph.com/sourcegraph.com/sourcegraph/srclib-python@master/.GoPackage/sourcegraph.com/sourcegraph/srclib-python/python/.def/Scan)) for historical reasons (just haven't ported it yet), but most of the work is done by [pydep](https://github.com/sourcegraph/pydep). The `pydep-run.py list <DIR>` command returns a list of all Python packages in the given directory tree. Pydep is also what resolves dependencies from, e.g., a project's requirements.txt file.

So, the scanner and dep resolver don't really involve Jedi. The Jedi-based grapher just consumes the output they produce.

To make srclib-python pants-a"wear" (bad pun?), there are 2 steps:

1. Write a scanner that traverses a directory tree for Pants Python targets. (Pydep currently just [looks for setup.py files](https://sourcegraph.com/github.com/sourcegraph/pydep@96fdf7afd479e219acf7af865f21fa1f1fe2bf5b/.PipPackage/pydep/.def/pydep/setup_py/setup_dirs). You could do something similar except look for BUILD files, and then instead of [setup_info](https://sourcegraph.com/github.com/sourcegraph/pydep@96fdf7afd479e219acf7af865f21fa1f1fe2bf5b/.PipPackage/pydep/.def/pydep/setup_py/setup_info), your scanner could just perform the same kind of parsing/dumping of data from the Pants BUILD file.)

  The only really important pieces of information the scanner needs to output are: (1) the name of the Python target ("source unit" in srclib parlance), which should be unique within the repo; and (2) a list of `.py` files that are passed to the grapher. Once you have a Pants scanner that does this, you should be able to run it with the grapher and get nice output.

2. To resolve cross-target dependencies (at the Pants target level, but also at the source code level, so that calls to another target link to the def in that other target on Sourcegraph), you need to write a dep resolver. Because Pants encourages the use of a single repo (and Twitter has a single repo), this should be fairly easy. (Usually the hard part of writing a dep resolver is determining the repo clone URL for some arbitrary pip/etc. package, which you don't have to do in this case.)

  I'm a bit rusty on how the current Python dep resolver works, but it's something like this:
  * Pydep's dep output lets it construct a mapping from dependency packages or files (i.e., the dir or `.py` file that `import a.b.c` would import) to the dependency they come from. E.g., it knows that `/usr/lib/python3/dist-packages/oauthlib/oauthlib/common.py` belongs to the oauthlib dep (and it knows oauthlib's clone URL, or in your case just the name of the Pants target that produces oauthlib).
  * When the Jedi-based grapher encounters an `import` statement, it determines statically what file would be imported. And it statically analyzes the source of all deps, so it has already seen the imported object. It knows which file it was defined in, as well as the same for all other properties/methods/etc. of that object. Jedi exports this information on the [DefFile](https://github.com/sourcegraph/srclib-python/blob/0d29d6b2396b8aec098341f7c83e08917867dfa7/grapher/graph.py#L103) field of refs (i.e., what file was the def it points to defined in).
  * Then the final stage is handled in Go. The Ref is examined by [inferSourceUnit](https://github.com/sourcegraph/srclib-python/blob/0d29d6b2396b8aec098341f7c83e08917867dfa7/python/grapher.go#L129) and the mapping of files to dep packages is consulted to resolve the ref to the dep it points to.

So, the only thing different about Pants is the dependency file map. I think that Pants has a different layout and perhaps loads deps differently. But I imagine it's easy to get Pants to dump this information.

> c) Since srclib-python is relies on jedi (which in-turn uses disttools/setuptools) for static analysis, Is it better to create a separate toolchain based on pants? What parts of the current python tool chain be used for this analysis? If we were to replace just parts of the toolchain, what parts should we be replacing? Any pointers will be helpful.

I believe the srclib-python *grapher* is 100% independent of setuptools/disttools/pip/etc. So you can definitely reuse that.

I think a separate toolchain based on pants would make the most sense in the long term. It needn't provide any graphers; it can just have a scanner that outputs all kinds of different source units (Java/Scala/Python/etc.) from the BUILD files, and a dep resolver. In the [output for each source unit](https://srclib.org/toolchains/scanner-output/), you can specify the Ops map to tell srclib to use a different toolchain for the graph operation.

But it'd certainly be fine in the short term to just fork this repo and add a Python-only Pants scanner/depresolver.

Hope this helps!

**Comment by mansu** [comment]
Thanks for a detailed response. This is very helpful.

**Comment by beyang** [comment]
Routine cleanup. Please re-open if this is still an issue.
